version: '3.8'
services:
  back-office:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: backOffice
    expose:
      - 8080
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    restart: always



# comando: docker-compose -f docker-compose.prod.yaml up
